version: "3"

services:
  alertmanager-bot:
    container_name: alertmanager-bot
    command:
    - --alertmanager.url=http://localhost:9093
    - --log.level=info
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: "788268348"
      TELEGRAM_TOKEN: 1407832279:AAH0EjeDMJyH7u2YjV9Dk7fCyq4GxMx5-WI
    image: metalmatze/alertmanager-bot:0.4.2
    ports:
    - 8080:8080
    restart: always
    networks:
    - alertmanager-bot
networks:
  alertmanager-bot: {}
  
