global:
   resolve_timeout: 20s
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'telegram'
  #  routes:
  #    - match:
  #        severity: 'critical'
  #      receiver: 'email'
      #    - match:
      #  serverity: 'critical'
      #receiver: 'email'

receivers:
- name: 'telegram'
  webhook_configs:
  - url: 'http://192.168.21.254:8080/'

- name: 'email'
  email_configs:
  - to: 'recipient@gmail.com'
    from: 'email_id@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'email_id@gmail.com'
    auth_identity: 'email_id@gmail.com'
    auth_password: 'password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job', 'instance']

