global:
   resolve_timeout: 20s
route:
  # group by, if not has job or instance, new alter is group with alertname. alertmanager will send mess alert or resolved when has new altername. it have not send new mess when have job or instance
  group_by: ['alertname', 'job', 'instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'send-telegram'

# overide route
  routes:
    - matchers:
      - job=MCC
      receiver: 'send-telegram'
      active_time_intervals:
        - 'active_time'

receivers:
- name: 'send-telegram'
  webhook_configs:
    - send_resolved: true
      url: http://prometheus_bot:9087/alert/788268348

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job', 'instance']

#set time Active
time_intervals:
  - name: 'active_time'
    time_intervals:
      - weekdays: ['monday:friday']
# must has location, if don't have location system get time zone UTC
        location: 'Asia/Ho_Chi_Minh'
        times:
          - start_time: "07:00"
            end_time: "11:30"
