global:
   resolve_timeout: 10s
route:
  group_by: ['alertname', 'job','instance','name','type']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 30m
  receiver: 'send-telegram'
  routes:
    - matchers:
      - job="MCC"
      - job="VPN-Tinh"
      receiver: 'send-telegram'
      active_time_intervals:
        - 'active_time'

receivers:
  - name: 'default-receiver' # multi receivers
    webhook_configs:  # telegram
      - send_resolved: true
        url: http://192.168.21.254:9087/alert/ChatID

    slack_configs:    # slack
      - send_resolved: true
        channel: '#alert-sapo'
        api_url: 'Slack App URL'
        text: -|
            *Alert:* {{ .CommonLabels.alertname }} - *Severity:* {{ .CommonLabels.severity }}
            *Instance:* {{ .CommonLabels.instance }}
            *Type:* {{ .CommonLabels.type }} - *Name:* {{ .CommonLabels.name }}
            *Description:* {{ .CommonAnnotations.description }}
            *Status:* {{ .Status }}


inhibit_rules:
  - source_match:
      severity: 'VPN-Tinh-Down'
    target_match:
      severity: 'MCC-Down'
#      matchers: [ severity="warning" ]
    equal: ['alertname', 'name']

  - source_match:
      severity: 'VPN-Tinh-Down'
    target_match:
      severity: 'critical'
    equal: ['alertname', 'type']

time_intervals:
  - name: 'active_time'
    time_intervals:
      - weekdays: ['monday:friday']
        location: 'Asia/Ho_Chi_Minh'
        times:
          - start_time: "07:00"
            end_time: "19:00"

