version: '3.1'

volumes:
  prometheus_data: {}

services:
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus
    volumes:
      - ./:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
    ports:
      - 9090:9090
    restart: always
