global:
  scrape_interval: 15s
  scrape_timeout: 15s

  external_labels:
    environment: localhost.localdomain

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - prometheus:9090

  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/windows-node.json
    job_name: windows-node
    metrics_path: /metrics

  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/linux-node.json
    job_name: linux-node
    metrics_path: /metrics


#  - job_name: ping_exporter
#    metrics_path: /metrics
#    static_configs:
#    - targets:
#      - ping_exporter:9427

#Blackbox_http
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/icmp.json
    job_name: icmp
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
