{
 "title": "Blackbox",
 "description": "Blackbox",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blackbox",
    "query": "label_values(probe_success{job=\"blackbox\"},exporter)"
   },
   {
    "name": "job",
    "query": "label_values(up{exporter=~\"$blackbox\", job=\"blackbox\"},job)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(up{job=~'$job'},env)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{job=~'$job',env=~'$env'},service)"
   },
   {
    "name": "gametype",
    "label": "gametype",
    "query": "label_values(up{job=~'$job',env=~'$env',service=~'$service'},gametype)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{job=~'$job',env=~'$env',service=~'$service',gametype=~'$gametype'},instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total time spent testing $targets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS detection class phase time $targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=~'PING-OS-VM',instance=~'$targets'}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "$job Blackbox Status details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP detection class service status statistics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code)",
     "legendFormat": "http status {{ value }}"
    }
   ]
  },
  {
   "title": "Service connectivity statistics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{job=~'$job'})",
     "legendFormat": "{{ value }}"
    }
   ]
  }
 ]
}