{
 "title": "System",
 "description": "System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "CPU name",
    "query": "label_values(node_exporter_build_info{env='$env'},name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_exporter_build_info{name='$name'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "System Runtime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU core count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU usage (5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"}))) * 100"
    }
   ]
  },
  {
   "title": "Currently Open File Descriptor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Root Partition Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System average load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second (%)",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value. (Milliseconds Spent Doing I/Os)\n\nirate(node_disk_io_time_seconds_total[1m]):\n Calculate the rate per second: (last value - last previous value) / timestamp difference, ie: disk cost in 1 second The proportion of time in I/O operations.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_I/O operations per second %"
    }
   ]
  },
  {
   "title": "Memory information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "graph",
   "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    {
     "format": "iops",
     "label": "Read (-) / write (+) I / O ops / sec"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "graph",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "graph",
   "description": "Read time ms The number of seconds per disk partition read operation\n\nWrite time ms The number of seconds per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\nIO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "Upload (-) / download (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_inDownload"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_outUpload"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "graph",
   "description": "CurrEstab - The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - The average number of TCP connections that have been directly converted from the CLOSED state to the SYN-SENT state (within 1 minute)\n\nPassiveOpens - The average number of TCP connections that have been directly converted from the LISTEN state to the SYN-RCVD state (within 1 minute)\n\nTCP_alloc - The number of TCP sockets that have been allocated (established, applied to sk_buff)\n\nTCP_inuse - The number of TCP sockets being used (listening)\n\nTCP_tw - Number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}