version: '3.1'

volumes:
  grafana_data: {}

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./config.monitoring
    restart: always

