services:
  prometheus_bot:
    build: .
    container_name: prometheus_bot
    ports:
      - '9087:9087'
    volumes:
      - ./config/config.yaml:/config.yaml
      - ./config/template.tmpl:/template.tmpl
    restart: always
