{
 "title": "OpenWrt Wifi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Wifi Network Bitrate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "wifi_network_bitrate",
     "legendFormat": "{{device}}/{{ifname}} {{frequency}}GHz CH{{channel}} SSID {{ssid}}"
    }
   ]
  },
  {
   "title": "Wifi Station Signal Strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "max(wifi_station_signal) by (ifname,name)",
     "legendFormat": "{{ifname}}: {{name}}"
    }
   ]
  },
  {
   "title": "Wifi Network Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "wifi_network_signal",
     "legendFormat": "{{device}}/{{ifname}} {{frequency}}GHz CH{{channel}} SSID {{ssid}}"
    }
   ]
  },
  {
   "title": "Wifi Station Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "rx (-) / tx (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wifi_station_tx_packets[5m])) by (name)",
     "legendFormat": "out {{name}}"
    },
    {
     "expr": "sum(irate(wifi_station_rx_packets[5m])) by (name)",
     "legendFormat": "in {{name}}"
    }
   ]
  },
  {
   "title": "Wifi Network Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "wifi_network_quality",
     "legendFormat": "{{device}}/{{ifname}} {{frequency}}GHz CH{{channel}} SSID {{ssid}}"
    }
   ]
  }
 ]
}